### PR TITLE
Updates mean egg temp effect

### LINKED ISSUE #3: Update mean_egg_temp_effect to have the winter run specific value
See the Winter Run DSM for details (currently we update mean_egg_temp_effect in cache-data.

### PR DESCRIPTION
**Pull request by ErinCain**
Adds temp effect for each run and deletes existing temp effect that was only for spring and fall

Used the same naming convention that we have for DSMhabitat where there is a different rda for fr, sr, and wr 

Closes #3

### CODE REVIEW

**Review by ergz — COMMENTED** [review]
wonder if its better to combine these datasets into one dataframe with columns `watershed, fr, sr, wr` (where sr is spring run values as a column) called mean_egg_temp_effect. Then in the load_baseline_data within in each model we pick out the correct one. Its gonna be less documentation.

**Comment by ErinCain** [comment]
> wonder if its better to combine these datasets into one dataframe with columns `watershed, fr, sr, wr` (where sr is spring run values as a column) called mean_egg_temp_effect. Then in the load_baseline_data within in each model we pick out the correct one. Its gonna be less documentation.

I am happy to do them all in one dataframe. I agree that it would simplify the documentation. The reason I did it this way was to be consistent with how we did it in `DSMhabitat` for different runs.

**Comment by ergz** [comment]
can you add issues to the winterRUn and springRun models (I already added one for fall run) about updating the load baseline data function, the change should be really straightforward but needs to happen soon after we merge this into main

**Comment by ErinCain** [comment]
> can you add issues to the winterRUn and springRun models (I already added one for fall run) about updating the load baseline data function, the change should be really straightforward but needs to happen soon after we merge this into main

Yes. I will create this issues now.

**Pull request merged**
